Resources:
  # ====================================================================================================================
  # [DEFINITION] System Manager: Paramters
  # ====================================================================================================================


  # ====================================================================================================================
  # [DEFINITION] SECRET MANAGER: Parameters
  # ====================================================================================================================
  SecretsManagerAppConfigurationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:custom.secretsManagerAppConfiguration}
      Description: Application Configuration Secret
      GenerateSecretString:
        SecretStringTemplate: '{ "api_key": "${self:custom.appApiKey}", "jwt_key": "${self:custom.appJwtKey}" }'
        GenerateStringKey: jwt_key
        PasswordLength: 32
        ExcludePunctuation: true

  SecretsManagerDocumentDBConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:custom.secretsManagerDocumentdbConnection}
      Description: DocumentDB Cluster Connection Secret
      GenerateSecretString:
        SecretStringTemplate: '{ "database": "${self:custom.documentdbDatabaseName}", "username": "${self:custom.documentdbMasterUsername}", "password": "${self:custom.documentdbMasterPassword}" }'
        GenerateStringKey: _password
        PasswordLength: 32
        ExcludePunctuation: true

# ======================================================================================================================
# [OUTPUTS] INFORMATION > Log information
# ======================================================================================================================
Outputs:
  SecretsManagerAppConfigurationSecret:
    Description: Secrets keys for application configuration
    Value: !Ref SecretsManagerAppConfigurationSecret
  SecretsManagerDocumentDBConnectionSecret:
    Description: Secret Key for database connection
    Value: !Ref SecretsManagerDocumentDBConnectionSecret
