Resources:
  # ====================================================================================================================
  # [DEFINITION] CLOUDFRONT Distribution > Operation Webapp
  # ====================================================================================================================
  S3BucketBackofficeWebappDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3BucketBackofficeWebapp
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - DomainName: !Select [ 2, !Split [ "/", !GetAtt S3BucketBackofficeWebapp.WebsiteURL ] ]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ErrorCachingMinTTL: 10
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ErrorCachingMinTTL: 10
            ResponseCode: 200
            ResponsePagePath: /index.html
        # Aliases:
        #   - '${self:custom.cloudFrontBackofficeDomainName}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        # ViewerCertificate:
        #   AcmCertificateArn: ${self:custom.acmGlobalCertificateArn}
        #   SslSupportMethod: sni-only
    

  # ====================================================================================================================
  # [DEFINITION] Route53 RecordSet > DNS Records
  # ====================================================================================================================
  # WebsiteOperationDNSName:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneName: '${self:custom.route53DomainName}.'
  #     RecordSets:
  #     - Name: '${self:custom.cloudFrontBackofficeDomainName}'
  #       Type: A
  #       AliasTarget:
  #         HostedZoneId: ${self:custom.route53HostedZoneId}
  #         DNSName: !GetAtt S3BucketBackofficeWebappDistribution.DomainName

# ======================================================================================================================
# [OUTPUTS] INFORMATION > Log information
# ======================================================================================================================
Outputs:
  S3BucketBackofficeWebappDistributionDomain:
    Value: !GetAtt S3BucketBackofficeWebappDistribution.DomainName